### ISSUE TITLE
python3-ow has disappeared - alternatives?

### ISSUE THREAD

**Issue by silke-99** [matthewwall/weewx-owfs#6]
Hello, I'm trying to get this to run since it would be an awesome extension to my weather station setup, but I cannot seem to get past the python3-ow dependency hurdle.

My system is python3 and the python3-ow package has disappeared from all repos. I tried with alternatives like trio-owfs and pyownet, but running weewx-owfs fails (weewx starts up then crashes, running owfs.py from CLI returns AttributeError).

Is there any way to get this to work in today's package landscape?

Thanks a lot!

**Comment by glennmckechnie** [comment]
Not sure where Mathew is at the moment, but you will find a working fork of this driver at

https://github.com/glennmckechnie/weewx-owfs

pyownet and owserver are the requirements now that ow has gone missing. The README at that fork should hold enough info to expand on those dependencies, if not ask for clarification.

That said: 
AttributeError could mean anything without context.
You need to post the full trace, either from the CLI output or (I'd assume) from syslog where weewx will dump a trace.

**Comment by silke-99** [comment]
Awesome, using your fork has solved it! Thanks so much!
